In [1]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
import tensorflow as tf

In [5]:
tf.__version__

'2.3.0'

In [7]:
from tensorflow.keras.layers import Embedding

In [8]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [9]:
from tensorflow.keras.layers import Dense

In [10]:
from tensorflow.keras.layers import LSTM

In [12]:
from tensorflow.keras.models import Sequential

In [13]:
from tensorflow.keras.preprocessing.text import one_hot

In [14]:
data = pd.read_csv('/content/drive/My Drive/Googlecolab/Fakenewsdata.csv')
data.head()

id  ... label
0   0  ...     1
1   1  ...     0
2   2  ...     1
3   3  ...     1
4   4  ...     1

[5 rows x 5 columns]

In [16]:
X = data.drop('label',axis = 1)
X.head()

id  ...                                               text
0   0  ...  House Dem Aide: We Didn’t Even See Comey’s Let...
1   1  ...  Ever get the feeling your life circles the rou...
2   2  ...  Why the Truth Might Get You Fired October 29, ...
3   3  ...  Videos 15 Civilians Killed In Single US Airstr...
4   4  ...  Print \nAn Iranian woman has been sentenced to...

[5 rows x 4 columns]

In [17]:
data = data.dropna()

In [18]:
data.reset_index(inplace = True)  ## Since we had droped null values we are reseting indexes of data frame.

In [19]:
X1 = data.drop('label' , axis = 1)
X1.head()

index  ...                                               text
0      0  ...  House Dem Aide: We Didn’t Even See Comey’s Let...
1      1  ...  Ever get the feeling your life circles the rou...
2      2  ...  Why the Truth Might Get You Fired October 29, ...
3      3  ...  Videos 15 Civilians Killed In Single US Airstr...
4      4  ...  Print \nAn Iranian woman has been sentenced to...

[5 rows x 5 columns]

In [20]:
Y1 = data['label']
Y1.head()

0    1
1    0
2    1
3    1
4    1
Name: label, dtype: int64

In [22]:
X1.shape

(18285, 5)

In [23]:
Y1.shape

(18285,)

In [24]:
voc_size = 5000

In [25]:
import nltk

In [26]:
import re

In [28]:
from nltk.stem.porter import PorterStemmer

In [27]:
from nltk.corpus import stopwords

In [31]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [29]:
PS = PorterStemmer()

In [34]:
corpus = []
for i in range(0,len(X1)):
  review = re.sub('[^a-zA-Z]'," ",X1['title'][i])
  review = review.lower()
  review = review.split()

  review = [PS.stem(word) for word in review if not word in stopwords.words('english')]
  review = " ".join(review)
  corpus.append(review)

In [35]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [36]:
onehot_rep = [one_hot(words,voc_size)for words in corpus]
onehot_rep

[[3529, 856, 764, 2227, 410, 2763, 3693, 1599, 2872, 1357],
 [2636, 2494, 313, 4517, 1753, 803, 4677],
 [4832, 465, 671, 1416],
 [408, 2805, 4912, 4926, 3811, 4538],
 [235, 1753, 2840, 407, 2631, 2031, 1753, 1462, 4219, 3295],
 [3744,
  4109,
  4521,
  1487,
  2989,
  2625,
  1929,
  2577,
  2180,
  4139,
  2041,
  4461,
  1028,
  1959,
  4677],
 [570, 1908, 4089, 4228, 83, 2979, 897, 2567, 4877, 4219, 2408],
 [4561, 2027, 4773, 3231, 1010, 1375, 2625, 210, 4877, 4219, 2408],
 [1985, 3635, 3648, 1146, 3174, 4371, 3068, 1133, 2625, 4453],
 [2703, 1918, 1881, 2040, 2225, 4602, 4795, 3606],
 [2431, 1526, 631, 1721, 4713, 2266, 447, 3097, 181, 850, 4022],
 [4926, 1488, 410, 4371, 2625, 1010],
 [755, 4385, 3393, 4829, 4075, 1616, 3316, 4835, 4139],
 [2032, 3467, 2982, 478, 3443, 2452, 3407, 4877, 4219, 2408],
 [2089, 471, 4766, 4151, 948, 4877, 4219, 2408],
 [3104, 3496, 1338, 4060, 1880, 4335, 3055, 4624, 2094, 118],
 [3149, 1380, 2494],
 [4061, 1458, 579, 1487, 2625, 4862, 2376, 4677],
 [

In [38]:
sent_length = 20
embedded_docs = pad_sequences(onehot_rep,padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0 ... 1599 2872 1357]
 [   0    0    0 ... 1753  803 4677]
 [   0    0    0 ...  465  671 1416]
 ...
 [   0    0    0 ... 4877 4219 2408]
 [   0    0    0 ... 1861 4054 1005]
 [   0    0    0 ... 3772 3309  797]]


In [39]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 3529,
        856,  764, 2227,  410, 2763, 3693, 1599, 2872, 1357], dtype=int32)

In [40]:
embedding_vector_features = 40
model = Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length = sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation = 'sigmoid'))
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 20, 40)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               56400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [41]:
len(embedded_docs),Y1.shape

(18285, (18285,))

In [42]:
X_final = np.array(embedded_docs)
Y_final = np.array(Y1) 

In [43]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_final,Y_final, test_size = 0.33, random_state = 42)

In [44]:
model.fit(X_train,Y_train, batch_size = 64, epochs = 10, validation_data=(X_test,Y_test))

Epoch 1/10
192/192 [==============================] - 6s 32ms/step - loss: 0.3349 - accuracy: 0.8429 - val_loss: 0.1944 - val_accuracy: 0.9158
Epoch 2/10
192/192 [==============================] - 6s 30ms/step - loss: 0.1407 - accuracy: 0.9447 - val_loss: 0.1907 - val_accuracy: 0.9200
Epoch 3/10
192/192 [==============================] - 6s 30ms/step - loss: 0.0960 - accuracy: 0.9651 - val_loss: 0.2005 - val_accuracy: 0.9168
Epoch 4/10
192/192 [==============================] - 6s 30ms/step - loss: 0.0669 - accuracy: 0.9752 - val_loss: 0.2249 - val_accuracy: 0.9158
Epoch 5/10
192/192 [==============================] - 6s 30ms/step - loss: 0.0416 - accuracy: 0.9864 - val_loss: 0.2837 - val_accuracy: 0.9175
Epoch 6/10
192/192 [==============================] - 6s 30ms/step - loss: 0.0249 - accuracy: 0.9930 - val_loss: 0.3688 - val_accuracy: 0.9135
Epoch 7/10
192/192 [==============================] - 6s 30ms/step - loss: 0.0161 - accuracy: 0.9955 - val_loss: 0.3701 - val_accuracy: 0.9143

In [52]:
Y_pred = model.predict_classes(X_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [53]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test,Y_pred)

array([[3098,  321],
       [ 198, 2418]])

In [54]:
confusion_matrix(Y_pred,Y_test)

array([[3098,  198],
       [ 321, 2418]])

In [55]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,Y_pred)

0.9140016570008285