In [21]:
import numpy as np

In [22]:
import pandas as pd

In [23]:
df = pd.read_csv('creditcard.csv')
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [24]:
df.shape

(284807, 31)

In [25]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [26]:
X = df.drop('Class', axis =1)
X.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V20       V21       V22       V23       V24  \
0  0.098698  0.363787  ...  0.251412 -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425  ... -0.069083 -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  ...  0.524980  0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024  ... -0.208038 -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  ...  0.408542 -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  
0  0.128539 -0.189115  0.133558 -0.021053  149.62  
1  0.167170  0.125895 -0.008983  0.014724    2.69  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66  
3  0.647376 -0.221929  0.062723  0.061458  123.50  
4 -0.206010  0.502292  0.219422  0.215153   69.99  

[5 rows x 30 columns]

In [27]:
Y = df['Class']
Y.head()

0    0
1    0
2    0
3    0
4    0
Name: Class, dtype: int64

# Cross Validation Like KFOLD and Hyperpaqrameter Tuning

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV

In [29]:
LR = LogisticRegression()
grid = {'C' : 10.0  **np.arange(-2,3), 'penalty' : ['l1','l2']}
cv = KFold(n_splits =5,random_state = None, shuffle = False)

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size = 0.3)

In [31]:
clf = GridSearchCV(LR,grid,cv=cv,n_jobs = 1,scoring = 'f1_macro')
clf.fit(X_train,Y_train)

D:\Anaconda\envs\pytorchenv\lib\site-packages\sklearn\model_selection\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "D:\Anaconda\envs\pytorchenv\lib\site-packages\sklearn\model_selection\_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "D:\Anaconda\envs\pytorchenv\lib\site-packages\sklearn\linear_model\_logistic.py", line 1304, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "D:\Anaconda\envs\pytorchenv\lib\site-packages\sklearn\linear_model\_logistic.py", line 443, in _check_solver
    "got %s penalty." % (solver, penalty))
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

  FitFailedWarning)
D:\Anaconda\envs\pytorchenv\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status

D:\Anaconda\envs\pytorchenv\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
D:\Anaconda\envs\pytorchenv\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logist

D:\Anaconda\envs\pytorchenv\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [32]:
pred = clf.predict(X_test)
print(confusion_matrix(Y_test,pred))
print(accuracy_score(Y_test,pred))
print(classification_report(Y_test,pred))

[[85260    41]
 [   41   101]]
0.9990402958697612
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85301
           1       0.71      0.71      0.71       142

    accuracy                           1.00     85443
   macro avg       0.86      0.86      0.86     85443
weighted avg       1.00      1.00      1.00     85443



In [35]:
class_weight = dict({0:1,1:100})

In [36]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(class_weight = class_weight)
classifier.fit(X_train,Y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [37]:
Y_pred = classifier.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[85294     7]
 [   26   116]]
0.9996137776061234
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85301
           1       0.94      0.82      0.88       142

    accuracy                           1.00     85443
   macro avg       0.97      0.91      0.94     85443
weighted avg       1.00      1.00      1.00     85443



# Sampling Techniques

######Under Sampling

In [39]:
from collections import Counter

In [40]:
Counter(Y_train)

Counter({0: 199014, 1: 350})

In [41]:
from collections import Counter
from imblearn.under_sampling import NearMiss

In [42]:
ns = NearMiss(0.8) ## It will reduce the '0' data 199014 to get until 80% of x value is equal to 350 (i.e., x*0.8 = 350)

D:\Anaconda\envs\pytorchenv\lib\site-packages\imblearn\utils\_validation.py:638: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning)


In [43]:
X_train_ns, Y_train_ns = ns.fit_sample(X_train,Y_train)
print('The number of classes before sampling {}' .format(Counter(Y_train)))
print('The number of classes after sampling {}' .format(Counter(Y_train_ns)))

The number of classes before sampling Counter({0: 199014, 1: 350})
The number of classes after sampling Counter({0: 437, 1: 350})


In [44]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier()

In [45]:
RF.fit(X_train_ns,Y_train_ns)

RandomForestClassifier()

In [47]:
Y_pred = RF.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[60668 24633]
 [    6   136]]
0.7116323162810294
              precision    recall  f1-score   support

           0       1.00      0.71      0.83     85301
           1       0.01      0.96      0.01       142

    accuracy                           0.71     85443
   macro avg       0.50      0.83      0.42     85443
weighted avg       1.00      0.71      0.83     85443



# Over Sampling 

In [48]:
from imblearn.over_sampling import RandomOverSampler

In [50]:
os = RandomOverSampler(0.75)
X_train_ns,Y_train_ns =os.fit_sample(X_train,Y_train)
print('The number of classes before sampling : {}'.format(Counter(Y_train)))
print('The number of classes after sampling : {}'.format(Counter(Y_train_ns)))

D:\Anaconda\envs\pytorchenv\lib\site-packages\imblearn\utils\_validation.py:638: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning)


The number of classes before sampling : Counter({0: 199014, 1: 350})
The number of classes after sampling : Counter({0: 199014, 1: 149260})


In [51]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train_ns,Y_train_ns)

RandomForestClassifier()

In [52]:
Y_pred = classifier.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[85293     8]
 [   25   117]]
0.9996137776061234
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85301
           1       0.94      0.82      0.88       142

    accuracy                           1.00     85443
   macro avg       0.97      0.91      0.94     85443
weighted avg       1.00      1.00      1.00     85443



# SMOTE Tomek

In [54]:
from imblearn.combine import SMOTETomek

In [57]:
ST = SMOTETomek(0.75)
X_train_ns, Y_train_ns = ST.fit_sample(X_train,Y_train)
print('The number of samples before sampling :{}'.format(Counter(Y_train)))
print('The number of samples after sampling :{}'.format(Counter(Y_train_ns)))

D:\Anaconda\envs\pytorchenv\lib\site-packages\imblearn\utils\_validation.py:638: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  FutureWarning)


The number of samples before sampling :Counter({0: 199014, 1: 350})
The number of samples after sampling :Counter({0: 198228, 1: 148474})


In [58]:
from sklearn.ensemble import RandomForestClassifier
RFC = RandomForestClassifier()

In [59]:
RFC.fit(X_train_ns,Y_train_ns)

RandomForestClassifier()

In [61]:
Y_Pred = RFC.predict(X_test)
print(confusion_matrix(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[85293     8]
 [   25   117]]
0.9996137776061234
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85301
           1       0.94      0.82      0.88       142

    accuracy                           1.00     85443
   macro avg       0.97      0.91      0.94     85443
weighted avg       1.00      1.00      1.00     85443

